apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "com.curva.ppob"
        minSdkVersion 19  // KITA KEMBALI KE 19
        targetSdkVersion 28
        versionCode 5     // NANTI JANGAN LUPA DIUBAH JIKA INGIN TES POPUP
        versionName "5.3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // KITA HAPUS APPCOMPAT KARENA ANDA HANYA PAKAI ACTIVITY BIASA
    // KITA HAPUS ORG.JSON KARENA ANDROID SUDAH PUNYA BAWAAN PABRIK

    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'
    implementation 'com.google.firebase:firebase-iid:18.0.0'
    
    // Zxing Scanner
    implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
}

